import ExcelJS from 'exceljs';
import { db } from '../store/repository.js';
import { getExcelTemplate } from './excelTemplateRegistry.js';
import { createExcelSnapshot, fingerprintRecords } from './excelSnapshots.js';
import crypto from 'node:crypto';

const DEFAULT_DATE = () => new Date().toISOString().slice(0, 10);
const safe = value => value === null || value === undefined ? '' : value;
const displayName = person => person?.fullName || person?.name || person?.personnelName || '';

const reportHeader = (worksheet, title, template, asOfDate) => {
  worksheet.mergeCells('A1:H1');
  worksheet.getCell('A1').value = title;
  worksheet.getCell('A1').font = { bold: true, size: 16, color: { argb: 'FFFFFFFF' } };
  worksheet.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '17365D' } };
  worksheet.getCell('A2').value = 'PAIS generated report';
  worksheet.getCell('B2').value = 'As of date';
  worksheet.getCell('C2').value = asOfDate;
  worksheet.getCell('D2').value = 'Template';
  worksheet.getCell('E2').value = template.id;
  worksheet.getCell('F2').value = 'Version';
  worksheet.getCell('G2').value = template.version;
  worksheet.getCell('A3').value = 'CONFIDENTIAL - For authorized PAIS users only';
  worksheet.getCell('A3').font = { italic: true, color: { argb: '9C0006' } };
  worksheet.getRow(2).font = { size: 9, color: { argb: '666666' } };
};

const addTable = (worksheet, headers, rows, options = {}) => {
  const headerRow = options.headerRow || 5;
  const dataStartRow = options.dataStartRow || headerRow + 1;
  worksheet.getRow(headerRow).values = headers;
  worksheet.getRow(headerRow).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  worksheet.getRow(headerRow).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '1F4E78' } };
  worksheet.getRow(headerRow).alignment = { vertical: 'middle', wrapText: true };
  rows.forEach((row, index) => {
    const target = worksheet.getRow(dataStartRow + index);
    target.values = row;
    target.alignment = { vertical: 'top', wrapText: true };
  });
  headers.forEach((header, index) => {
    worksheet.getColumn(index + 1).width = Math.min(Math.max(String(header).length + 4, 14), 32);
  });
  worksheet.views = [{ state: 'frozen', ySplit: headerRow }];
  worksheet.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow, column: headers.length } };
};

const protect = worksheet => worksheet.protect('PAIS-generated', {
  selectLockedCells: true,
  selectUnlockedCells: true,
  formatColumns: false,
  formatRows: false,
  insertRows: false,
  deleteRows: false
});

const normalized = value => String(value ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
const strengthKey = (reportType, unitKey = '', rankKey = '') => `${reportType}\u0000${normalized(unitKey)}\u0000${normalized(rankKey)}`;
const authorizedValue = (authorized, reportType, unitKey = '', rankKey = '') => authorized.get(strengthKey(reportType, unitKey, rankKey)) ?? '';

const addMetadataSheet = (workbook, template, asOfDate, status, exportId) => {
  const sheet = workbook.addWorksheet('PAIS Metadata');
  sheet.state = 'veryHidden';
  sheet.addRows([
    ['Template ID', template.id], ['Template Version', template.version], ['Reference File', template.referenceFile],
    ['Generated As Of', asOfDate], ['Personnel Status', status], ['Export ID', exportId], ['Generated By', 'PAIS 2.0'],
    ['Editable Fields', template.editPolicy?.editableFields?.join(', ') || 'None'],
    ['Locked Fields', template.editPolicy?.lockedFields?.join(', ') || 'All generated fields']
  ]);
  sheet.getColumn(1).width = 24; sheet.getColumn(2).width = 90;
};

const applyEditPolicy = (worksheet, template, headerRow, dataStartRow, dataRowCount) => {
  worksheet.eachRow(row => row.eachCell(cell => { cell.protection = { locked: true }; }));
  const editable = new Set(template.editPolicy?.editableFields || []);
  template.fieldMappings.forEach(mapping => {
    if (!editable.has(mapping.target)) return;
    let columnNumber = null;
    worksheet.getRow(headerRow).eachCell((cell, index) => {
      if (mapping.headerAliases.some(alias => normalized(alias) === normalized(cell.value))) columnNumber = index;
    });
    if (columnNumber) for (let row = dataStartRow; row < dataStartRow + dataRowCount; row += 1) worksheet.getCell(row, columnNumber).protection = { locked: false };
  });
};

const personnelRows = (people, asOfDate) => people.map(person => [
  safe(person.badgeNo || person.personnelId || person.id), displayName(person), safe(person.rank),
  safe(person.rankCategory), safe(person.unitCategory || person.sub_unit || person.division),
  safe(person.sub_unit || person.division), safe(person.station), safe(person.status), asOfDate
]);

const groupedRankRows = people => {
  const groups = new Map();
  people.forEach(person => {
    const unit = person.unitCategory || person.sub_unit || person.division || 'Unassigned';
    const rank = person.rank || 'Unassigned';
    const key = `${unit}\u0000${rank}`;
    groups.set(key, (groups.get(key) || 0) + 1);
  });
  return [...groups.entries()].sort().map(([key, count]) => {
    const [unit, rank] = key.split('\u0000');
    return [unit, rank, count];
  });
};

const groupedCategoryRows = people => [...new Set(people.map(person => person.unitCategory || person.sub_unit || person.division || 'Unassigned'))].sort().map(unit => {
  const records = people.filter(person => (person.unitCategory || person.sub_unit || person.division || 'Unassigned') === unit);
  const count = category => records.filter(person => category === 'NUP' ? person.rankCategory === 'NUP' : category === person.rankCategory).length;
  return [unit, count('PCO'), count('PNCO'), count('NUP'), ''];
});

const exportTraining = (worksheet, template, records, people, asOfDate) => {
  const names = new Map(people.map(person => [person.id, displayName(person)]));
  const ranks = new Map(people.map(person => [person.id, person.rank]));
  const headers = ['Personnel ID', 'Personnel Name', 'Training Type', 'Training Title', 'School/Provider', 'Start Date', 'End Date', 'Hours', 'Auth Number'];
  const rows = records.map(record => [
    safe(record.personnelId), names.get(record.personnelId) || safe(record.personnelName), safe(record.category),
    safe(record.courseName), safe(record.provider || record.issuedBy), safe(record.startDate), safe(record.completionDate || record.endDate),
    safe(record.hours), safe(record.certificateNo || record.orderNumber)
  ]);
  addTable(worksheet, headers, rows, { headerRow: 1, dataStartRow: 2 });
  worksheet.getCell('A1').note = `PAIS Training Records | ${asOfDate} | Template ${template.version}`;
};

const exportEducation = (worksheet, template, records, people, asOfDate) => {
  const names = new Map(people.map(person => [person.id, displayName(person)]));
  const headers = ['Personnel ID', 'Personnel Name', 'Academic Level', 'Institution', 'Degree/Course', 'Major', 'Start Year', 'Year Graduated', 'Honors', 'Highest', 'Ranking'];
  const rows = records.map(record => [safe(record.personnelId), names.get(record.personnelId) || safe(record.personnelName), safe(record.academicLevel), safe(record.institution || record.school), safe(record.degree || record.course), safe(record.major), safe(record.startYear), safe(record.yearGraduated || record.endYear), safe(record.honors), safe(record.highest), safe(record.ranking)]);
  addTable(worksheet, headers, rows, { headerRow: 1, dataStartRow: 2 });
  worksheet.getCell('A1').note = `PAIS Education Records | ${asOfDate} | Template ${template.version}`;
};

const exportPersonnel = (worksheet, template, people, asOfDate, definition, authorized = new Map()) => {
  if (template.id === 'statistics-by-rank') {
    const ranks = ['PBGEN', 'PCOL', 'PLTCOL', 'PMAJ', 'PCPT', 'PLT', 'PEMS', 'PCMS', 'PSMS', 'PMSg', 'PSSg', 'PCpl', 'Pat'];
    const groups = [...new Set(people.map(person => person.unitCategory || person.sub_unit || person.division || 'Unassigned'))].sort();
    const rows = groups.map((unit, index) => {
      const records = people.filter(person => (person.unitCategory || person.sub_unit || person.division || 'Unassigned') === unit);
      const counts = ranks.map(rank => records.filter(person => String(person.rank || '') === rank).length);
      return [unit, { formula: `I${6 + index}+P${6 + index}` }, ...counts.slice(0, 6), { formula: `SUM(C${6 + index}:H${6 + index})` }, ...counts.slice(6), { formula: `SUM(J${6 + index}:O${6 + index})` }, { formula: `I${6 + index}+P${6 + index}` }];
    });
    addTable(worksheet, ['OFFICE', 'POPULATION', ...ranks.slice(0, 6), 'TOTAL', ...ranks.slice(6), 'TOTAL', 'GRAND TOTAL'], rows, { headerRow: 5, dataStartRow: 6 });
    return;
  }
  if (definition.name === 'Rank Profile') {
    const rows = [...new Set(people.map(person => person.rank || 'Unassigned'))].sort().map((rank, index) => {
      const records = people.filter(person => (person.rank || 'Unassigned') === rank);
      const male = records.filter(person => String(person.gender || '').toLowerCase() === 'male').length;
      const female = records.filter(person => String(person.gender || '').toLowerCase() === 'female').length;
      return [rank, authorizedValue(authorized, 'rank-profile', '', rank), male, female, { formula: `SUM(C${11 + index}:D${11 + index})` }];
    });
    addTable(worksheet, ['RANK', 'AUTHORIZED STRENGTH', 'MALE', 'FEMALE', 'TOTAL'], rows, { headerRow: 10, dataStartRow: 11 });
    return;
  }
  if (definition.name === 'Territorial Strength') {
    const rows = groupedCategoryRows(people).map((row, index) => [...row.slice(0, 4), { formula: `SUM(B${10 + index}:D${10 + index})` }]);
    addTable(worksheet, ['OFFICE/UNIT', 'PCOs', 'PNCOs', 'NUP', 'TOTAL'], rows, { headerRow: 9, dataStartRow: 10 });
    return;
  }
  if (definition.name.startsWith('Statistics')) {
    if (definition.name === 'Statistics NUP') {
      const grades = ['SG-4', 'SG-5', 'SG-6', 'SG-7', 'SG-8', 'SG-9', 'SG-10', 'SG-11', 'SG-12', 'SG-13', 'SG-14', 'SG-15', 'SG-16', 'SG-17', 'SG-18'];
      const counts = grades.map(grade => people.filter(person => normalized(person.rankCategory) === 'nup' && normalized(person.salaryGrade).replace(/^sg[- ]?/, '') === grade.replace('SG-', '')).length);
      addTable(worksheet, ['STATUS', ...grades, 'GRAND TOTAL'], [['Active', ...counts, { formula: 'SUM(B12:P12)' }]], { headerRow: 11, dataStartRow: 12 });
    } else {
      const pcoRanks = ['PBGEN', 'PCOL', 'PLTCOL', 'PMAJ', 'PCPT', 'PLT'];
      const pncoRanks = ['PEMS', 'PCMS', 'PSMS', 'PMSg', 'PSSg', 'PCpl', 'Pat'];
      const pcoCounts = pcoRanks.map(rank => people.filter(person => String(person.rank || '') === rank).length);
      const pncoCounts = pncoRanks.map(rank => people.filter(person => String(person.rank || '') === rank).length);
      addTable(worksheet, ['STATUS', ...pcoRanks, 'PCO Total', ...pncoRanks, 'PNCO Total', 'GRAND Total'], [['Active', ...pcoCounts, { formula: 'SUM(B12:G12)' }, ...pncoCounts, { formula: 'SUM(I12:O12)' }, { formula: 'H12+P12' }]], { headerRow: 11, dataStartRow: 12 });
    }
    return;
  }
  if (definition.name === 'HQ ITMS') {
    const rows = [...new Set(people.map(person => person.details || person.designation || 'Unassigned'))].sort().map(designation => {
      const count = people.filter(person => (person.details || person.designation || 'Unassigned') === designation).length;
      const row = 10 + [...new Set(people.map(person => person.details || person.designation || 'Unassigned'))].sort().indexOf(designation);
      return [designation, 'All', authorizedValue(authorized, 'hq-itms', designation, 'All'), count, { formula: `D${row}-C${row}` }];
    });
    addTable(worksheet, ['DESIGNATION', 'RANK', 'AUTHORIZED STRENGTH', 'ACTUAL STRENGTH', 'VARIANCE'], rows, { headerRow: 9, dataStartRow: 10 });
    return;
  }
  addTable(worksheet, ['Personnel ID', 'Name', 'Rank', 'Category', 'Office/Unit', 'Division', 'Station', 'Status', 'As Of Date'], personnelRows(people, asOfDate), { headerRow: 9, dataStartRow: 10 });
};

const factorValue = (evaluation, key) => evaluation.calculation?.factors?.find(factor => factor.key === key) || {};

const exportPromotion = (worksheet, template, evaluations, people, asOfDate, definition) => {
  const names = new Map(people.map(person => [person.id, displayName(person)]));
  const filtered = evaluations.filter(item => !template.promotionTrack || String(item.calculation?.scoringConfiguration?.version || '').includes(template.promotionTrack));
  const rows = filtered.map(item => {
    const seniority = factorValue(item, 'seniority');
    const diversity = factorValue(item, 'diversity');
    const awards = factorValue(item, 'awards');
    const reputation = factorValue(item, 'serviceReputation');
    const interview = factorValue(item, 'interviewRating');
    const other = factorValue(item, 'otherQualifications');
    const base = [safe(item.personnelId), names.get(item.personnelId) || '', safe(item.calculation?.evaluationDate || item.evaluationDate), safe(item.status), safe(item.calculation?.totalPoints), safe(item.calculation?.scoringConfiguration?.version)];
    if (definition?.factor === 'seniority') return [base[0], base[1], safe(ranks.get(item.personnelId)), base[2], safe(seniority.value?.promotionDate), safe(seniority.value?.days), safe(seniority.value?.duration), safe(seniority.points), safe(seniority.status)];
    if (definition?.factor === 'awards') return [base[0], base[1], base[2], safe(awards.value?.count), safe(awards.points), safe(awards.maxPoints), safe(awards.status)];
    if (definition?.factor === 'diversity') return [base[0], base[1], base[2], safe(diversity.value?.Luzon?.days), safe(diversity.value?.Visayas?.days), safe(diversity.value?.Mindanao?.days), safe(diversity.points), safe(diversity.status)];
    if (definition?.factor === 'serviceReputation') return [base[0], base[1], base[2], safe(reputation.value), safe(reputation.points), safe(reputation.maxPoints), safe(reputation.remarks), safe(reputation.status)];
    if (definition?.factor === 'interviewRating') return [base[0], base[1], base[2], safe(interview.value), safe(interview.points), safe(interview.maxPoints), safe(interview.remarks), safe(interview.status)];
    if (definition?.factor === 'otherQualifications') return [base[0], base[1], base[2], safe(other.value), safe(other.points), safe(other.maxPoints), safe(other.remarks), safe(other.status)];
    return [...base, safe(item.remarks)];
  });
  const config = filtered[0]?.calculation?.scoringConfiguration?.factors || {};
  const factor = definition?.factor;
  const headers = factor === 'seniority'
    ? ['Personnel ID', 'Personnel Name', 'Rank', 'Evaluation Date', 'Promotion Date', 'Seniority Days', 'Duration', 'Seniority Points', 'Status']
    : factor === 'awards'
      ? ['Personnel ID', 'Personnel Name', 'Evaluation Date', 'Award Count', 'Awards Points', 'Maximum Points', 'Status']
      : factor === 'diversity'
        ? ['Personnel ID', 'Personnel Name', 'Evaluation Date', 'Luzon Days', 'Visayas Days', 'Mindanao Days', 'Diversity Points', 'Status']
        : factor
          ? ['Personnel ID', 'Personnel Name', 'Evaluation Date', 'Value', 'Points', 'Maximum Points', 'Remarks', 'Status']
          : ['Personnel ID', 'Personnel Name', 'Evaluation Date', 'Status', 'Total Score', 'Scoring Configuration', 'Remarks'];
  reportHeader(worksheet, definition?.name || template.name, template, asOfDate);
  addTable(worksheet, headers, rows, { headerRow: definition?.headerRow || 5, dataStartRow: definition?.dataStartRow || 6 });
  worksheet.getCell('A4').value = `Reference maxima: ${factor ? safe(config[factor]) : 'See factor worksheets'} | Automatic points remain pending policy approval.`;
  worksheet.getCell('A4').font = { italic: true, color: { argb: '7F6000' } };
};

export const generateExcelExport = async ({ templateId, asOfDate = DEFAULT_DATE(), status = 'Active' }) => {
  const template = getExcelTemplate(templateId);
  if (!template) {
    const error = new Error('Excel template definition not found.');
    error.statusCode = 404;
    throw error;
  }

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'PAIS 2.0';
  workbook.company = 'PNP Information Technology Management Service';
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.properties = { subject: template.name, keywords: `PAIS,${template.id},${template.version}` };
  const exportId = crypto.randomUUID();
  addMetadataSheet(workbook, template, asOfDate, status, exportId);

  const people = await db.getPersonnel({ status });
  const authorized = new Map((templateId === 'personnel-disposition-reports'
    ? await db.getAuthorizedStrengths({ asOfDate })
    : []).map(item => [strengthKey(item.reportType, item.unitKey, item.rankKey), item.authorizedStrength]));
  let sourceRecords = people;
  if (templateId === 'training-import') {
    const sheet = workbook.addWorksheet('TRAINING');
    sourceRecords = await db.getTraining();
    exportTraining(sheet, template, sourceRecords, people, asOfDate);
  } else if (templateId === 'education-import') {
    const sheet = workbook.addWorksheet('EDUCATION');
    sourceRecords = await db.getEducation();
    exportEducation(sheet, template, sourceRecords, people, asOfDate);
  } else if (templateId === 'statistics-by-rank') {
    const sheet = workbook.addWorksheet('Statistics by Rank');
    exportPersonnel(sheet, template, people, asOfDate, template.sheets[0], authorized);
  } else if (templateId === 'personnel-disposition-reports') {
    template.sheets.forEach(definition => {
      const sheet = workbook.addWorksheet(definition.name);
      exportPersonnel(sheet, template, people, asOfDate, definition, authorized);
    });
  } else {
    const evaluations = await db.getPromotionEvaluations();
    template.sheets.forEach(definition => {
      const sheet = workbook.addWorksheet(definition.name);
      exportPromotion(sheet, template, evaluations, people, asOfDate, definition);
    });
  }

  for (const sheet of workbook.worksheets) {
    const definition = template.sheets.find(item => item.name === sheet.name);
    if (definition) applyEditPolicy(sheet, template, definition.headerRow === 1 ? 1 : (definition.headerRow || 5), definition.dataStartRow || 6, Math.max(0, sheet.rowCount - (definition.dataStartRow || 6) + 1));
    await protect(sheet);
  }

  const snapshotSheets = workbook.worksheets.filter(sheet => sheet.name !== 'PAIS Metadata').map(sheet => ({
    name: sheet.name,
    rows: Array.from({ length: sheet.rowCount }, (_, rowIndex) => Array.from({ length: sheet.columnCount }, (_, columnIndex) => safe(sheet.getRow(rowIndex + 1).getCell(columnIndex + 1).value)))
  }));
  createExcelSnapshot({ exportId, templateId, templateVersion: template.version, sheets: snapshotSheets, sourceFingerprint: fingerprintRecords(sourceRecords) });
  const buffer = await workbook.xlsx.writeBuffer();
  return { buffer, filename: `${templateId}-${asOfDate}.xlsx`, template, exportId };
};

export const generateExcelPreview = async options => {
  const { buffer, template, exportId } = await generateExcelExport(options);
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);
  const sheets = workbook.worksheets
    .filter(sheet => sheet.name !== 'PAIS Metadata' && sheet.state === 'visible')
    .map(sheet => ({
      name: sheet.name,
      rowCount: sheet.rowCount,
      columnCount: sheet.columnCount,
      rows: Array.from({ length: sheet.rowCount }, (_, rowIndex) => Array.from({ length: sheet.columnCount }, (_, columnIndex) => {
        const value = sheet.getRow(rowIndex + 1).getCell(columnIndex + 1).value;
        if (value && typeof value === 'object' && 'formula' in value) return `=${value.formula}`;
        if (value instanceof Date) return value.toISOString().slice(0, 10);
        return value === null || value === undefined ? '' : value;
      }))
    }));
  return { template, exportId, sheets };
};
