export const INITIAL_PERSONNEL = [
  {
    id: 'pnp-001',
    rank: 'PCOL',
    rankFullName: 'Police Colonel',
    firstName: 'RODRIGO',
    middleName: 'SANTOS',
    lastName: 'DELA CRUZ',
    qualifier: 'JR.',
    fullName: 'PCOL RODRIGO S. DELA CRUZ JR.',
    badgeNo: '0-114829',
    salaryGrade: 26,
    plantilla: 'ITMS-DIR-2024-001',
    division: 'ARMD',
    detail: 'ITMS Headquarters - Camp BGen Rafael T Crame',
    designation: 'Chief, Administrative & Resource Management Division',
    address: '124 Col. Bonny Serrano Ave, Quezon City, Metro Manila',
    gender: 'Male',
    contactNumber: '0917-882-1920',
    birthday: '1975-08-14',
    dateOfEntry: '1998-04-16',
    enterInOfficerPositionDate: '2001-06-01',
    lastPromotionDate: '2021-03-15',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-002',
    rank: 'PLTCOL',
    rankFullName: 'Police Lieutenant Colonel',
    firstName: 'MARIA',
    middleName: 'CORAZON',
    lastName: 'REYES',
    fullName: 'PLTCOL MARIA CORAZON REYES',
    badgeNo: '0-128490',
    salaryGrade: 25,
    plantilla: 'ITMS-CSD-2024-002',
    division: 'CSD',
    detail: 'ITMS HQ - Cyber Defense Operations Center',
    designation: 'Chief, Cyber Security Division',
    address: '45 Katipunan Ave, Loyola Heights, Quezon City',
    gender: 'Female',
    contactNumber: '0918-554-3210',
    birthday: '1981-11-03',
    dateOfEntry: '2004-09-01',
    enterInOfficerPositionDate: '2007-02-15',
    lastPromotionDate: '2022-09-10',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-003',
    rank: 'PMAJ',
    rankFullName: 'Police Major',
    firstName: 'ANTONIO',
    middleName: 'BAUTISTA',
    lastName: 'MENDOZA',
    qualifier: 'III',
    fullName: 'PMAJ ANTONIO B. MENDOZA III',
    badgeNo: '0-139012',
    salaryGrade: 24,
    plantilla: 'ITMS-SDD-2024-005',
    division: 'SDD',
    detail: 'ITMS HQ - Software Development Division',
    designation: 'Lead Enterprise Software Architect',
    address: '88 West Avenue, Quezon City',
    gender: 'Male',
    contactNumber: '0920-441-9988',
    birthday: '1986-02-20',
    dateOfEntry: '2009-06-15',
    enterInOfficerPositionDate: '2012-08-01',
    lastPromotionDate: '2020-01-20',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-004',
    rank: 'PCPT',
    rankFullName: 'Police Captain',
    firstName: 'CATHERINE',
    middleName: 'LUMANOG',
    lastName: 'GARCIA',
    fullName: 'PCPT CATHERINE L. GARCIA',
    badgeNo: '0-145620',
    salaryGrade: 23,
    plantilla: 'ITMS-NDCMD-2024-012',
    division: 'NDCMD',
    detail: 'ITMS Network Operations Center',
    designation: 'Senior Infrastructure & Cloud Engineer',
    address: '15 Commonwealth Ave, Tandang Sora, Quezon City',
    gender: 'Female',
    contactNumber: '0919-332-1144',
    birthday: '1990-05-12',
    dateOfEntry: '2013-01-10',
    enterInOfficerPositionDate: '2015-05-20',
    lastPromotionDate: '2023-04-18',
    status: 'On Leave',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-005',
    rank: 'PLT',
    rankFullName: 'Police Lieutenant',
    firstName: 'JOHN',
    middleName: 'MARK',
    lastName: 'TORRES',
    fullName: 'PLT JOHN MARK TORRES',
    badgeNo: '0-158933',
    salaryGrade: 22,
    plantilla: 'ITMS-RITMO-2024-04A',
    division: 'RITMO 4A',
    detail: 'PRO4A Camp Vicente Lim, Calamba, Laguna',
    designation: 'Regional IT Officer - RITMO 4A',
    address: 'Brgy. Mayapa, Calamba City, Laguna',
    gender: 'Male',
    contactNumber: '0922-887-3311',
    birthday: '1993-09-28',
    dateOfEntry: '2016-03-01',
    enterInOfficerPositionDate: '2019-10-15',
    lastPromotionDate: '2023-11-05',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-006',
    rank: 'PEMS',
    rankFullName: 'Police Executive Master Sergeant',
    firstName: 'ERNESTO',
    middleName: 'VALDEZ',
    lastName: 'RAMOS',
    fullName: 'PEMS ERNESTO V. RAMOS',
    badgeNo: 'E-084201',
    salaryGrade: 19,
    plantilla: 'ITMS-OMD-2024-008',
    division: 'OMD',
    detail: 'ITMS Operations Center',
    designation: 'Chief Non-Commissioned Officer (NCOIC)',
    address: 'Cainta, Rizal',
    gender: 'Male',
    contactNumber: '0917-101-2030',
    birthday: '1976-12-05',
    dateOfEntry: '1997-08-10',
    enterInOfficerPositionDate: 'N/A',
    lastPromotionDate: '2019-07-01',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-007',
    rank: 'PCMS',
    rankFullName: 'Police Chief Master Sergeant',
    firstName: 'SHEILA',
    middleName: 'MAY',
    lastName: 'AQUINO',
    fullName: 'PCMS SHEILA MAY AQUINO',
    badgeNo: 'E-099415',
    salaryGrade: 18,
    plantilla: 'ITMS-PPD-2024-015',
    division: 'PPD',
    detail: 'ITMS HQ - Plans & Programs Division',
    designation: 'Senior IT Project Specialist',
    address: 'Marikina City, Metro Manila',
    gender: 'Female',
    contactNumber: '0998-765-4321',
    birthday: '1984-07-22',
    dateOfEntry: '2006-11-15',
    enterInOfficerPositionDate: 'N/A',
    lastPromotionDate: '2021-08-14',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'pnp-008',
    rank: 'PCPL',
    rankFullName: 'Police Corporal',
    firstName: 'KENNETH',
    middleName: 'DE GUZMAN',
    lastName: 'ALVAREZ',
    fullName: 'PCPL KENNETH D. ALVAREZ',
    badgeNo: 'E-123984',
    salaryGrade: 14,
    plantilla: 'ITMS-ISSD-2024-022',
    division: 'ISSD',
    detail: 'ITMS Systems Audit Unit',
    designation: 'Cyber Security Analyst / Auditor',
    address: 'Pasig City, Metro Manila',
    gender: 'Male',
    contactNumber: '0905-123-9900',
    birthday: '1996-03-14',
    dateOfEntry: '2019-05-20',
    enterInOfficerPositionDate: 'N/A',
    lastPromotionDate: '2022-12-01',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200'
  }
];

export const INITIAL_ASSIGNMENTS = [
  {
    id: 'asg-101',
    personnelId: 'pnp-001',
    unit: 'Administrative & Resource Management Division (ARMD)',
    position: 'Division Chief',
    orderRef: 'SO-ITMS-2024-045',
    startDate: '2023-01-15',
    status: 'Current',
    remarks: 'Reassigned as Chief, ARMD per Special Order No. 45'
  },
  {
    id: 'asg-102',
    personnelId: 'pnp-001',
    unit: 'Operations Management Division (OMD)',
    position: 'Assistant Chief',
    orderRef: 'SO-ITMS-2021-112',
    startDate: '2021-03-20',
    endDate: '2023-01-14',
    status: 'Completed',
    remarks: 'Commended for excellent service during National Elections 2022'
  },
  {
    id: 'asg-103',
    personnelId: 'pnp-002',
    unit: 'Cyber Security Division (CSD)',
    position: 'Chief, Cyber Security Division',
    orderRef: 'SO-ITMS-2023-019',
    startDate: '2022-10-01',
    status: 'Current',
    remarks: 'Leading national PNP Cyber Threat Intelligence Unit'
  },
  {
    id: 'asg-104',
    personnelId: 'pnp-003',
    unit: 'Systems Development Division (SDD)',
    position: 'Lead Software Architect',
    orderRef: 'SO-ITMS-2022-088',
    startDate: '2022-02-01',
    status: 'Current',
    remarks: 'Head architect for Online PAIS 2.0 & Crime Information Reporting System'
  },
  {
    id: 'asg-105',
    personnelId: 'pnp-004',
    unit: 'Network & Data Center Management Division (NDCMD)',
    position: 'Senior Infrastructure Engineer',
    orderRef: 'SO-ITMS-2023-092',
    startDate: '2023-05-01',
    status: 'Current'
  },
  {
    id: 'asg-106',
    personnelId: 'pnp-005',
    unit: 'RITMO 4A (CALABARZON)',
    position: 'Regional IT Officer',
    orderRef: 'SO-ITMS-2023-140',
    startDate: '2023-11-10',
    status: 'Current'
  }
];

export const INITIAL_EDUCATION = [
  {
    id: 'edu-201',
    personnelId: 'pnp-001',
    degree: 'Master in Public Administration (MPA)',
    institution: 'University of the Philippines Diliman',
    yearGraduated: 2012,
    honors: 'With High Distinction',
    certifications: ['Project Management Professional (PMP)', 'ITIL v4 Specialist']
  },
  {
    id: 'edu-202',
    personnelId: 'pnp-001',
    degree: 'BS Computer Science',
    institution: 'Philippine Military Academy (PMA Class of 1998)',
    yearGraduated: 1998,
    honors: 'Cum Laude',
    certifications: ['Certified Information Systems Auditor (CISA)']
  },
  {
    id: 'edu-203',
    personnelId: 'pnp-002',
    degree: 'MS Cyber Security & Information Assurance',
    institution: 'De La Salle University Manila',
    yearGraduated: 2015,
    certifications: ['CISSP - Certified Information Systems Security Professional', 'CEH - Certified Ethical Hacker', 'CompTIA Security+']
  },
  {
    id: 'edu-204',
    personnelId: 'pnp-003',
    degree: 'BS Information Technology',
    institution: 'Mapúa University',
    yearGraduated: 2008,
    honors: 'Magna Cum Laude',
    certifications: ['AWS Certified Solutions Architect - Professional', 'Oracle Certified Professional Java SE']
  },
  {
    id: 'edu-205',
    personnelId: 'pnp-004',
    degree: 'BS Computer Engineering',
    institution: 'Polytechnic University of the Philippines',
    yearGraduated: 2012,
    certifications: ['Cisco Certified Network Professional (CCNP)', 'Fortinet NSE 4']
  }
];

export const INITIAL_PROMOTIONS = [
  {
    id: 'prm-301',
    personnelId: 'pnp-001',
    rankFrom: 'PLTCOL',
    rankTo: 'PCOL',
    promotionDate: '2021-03-15',
    orderNumber: 'SO-DPRM-2021-0412',
    timeInGradeAtPromotion: '4 yrs, 2 mos',
    remarks: 'Promoted per National Police Commission Resolution No. 2021-098'
  },
  {
    id: 'prm-302',
    personnelId: 'pnp-001',
    rankFrom: 'PMAJ',
    rankTo: 'PLTCOL',
    promotionDate: '2017-01-10',
    orderNumber: 'SO-DPRM-2017-0105',
    timeInGradeAtPromotion: '3 yrs, 8 mos'
  },
  {
    id: 'prm-303',
    personnelId: 'pnp-002',
    rankFrom: 'PMAJ',
    rankTo: 'PLTCOL',
    promotionDate: '2022-09-10',
    orderNumber: 'SO-DPRM-2022-1102',
    timeInGradeAtPromotion: '4 yrs, 5 mos'
  },
  {
    id: 'prm-304',
    personnelId: 'pnp-003',
    rankFrom: 'PCPT',
    rankTo: 'PMAJ',
    promotionDate: '2020-01-20',
    orderNumber: 'SO-DPRM-2020-0089',
    timeInGradeAtPromotion: '3 yrs, 11 mos'
  },
  {
    id: 'prm-305',
    personnelId: 'pnp-004',
    rankFrom: 'PLT',
    rankTo: 'PCPT',
    promotionDate: '2023-04-18',
    orderNumber: 'SO-DPRM-2023-0341',
    timeInGradeAtPromotion: '3 yrs, 6 mos'
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'ord-401',
    orderNumber: 'SO-ITMS-2024-045',
    orderType: 'Assignment Order',
    subject: 'Reassignment of PCOL Rodrigo S Dela Cruz Jr as Chief, ARMD',
    issuedDate: '2024-01-10',
    effectiveDate: '2024-01-15',
    signatory: 'PBGEN BENJAMIN H ACORDA',
    signatoryTitle: 'Director, ITMS',
    status: 'Active',
    affectedPersonnelCount: 1,
    description: 'In the interest of the service and pursuant to NAPOLCOM guidelines, PCOL DELA CRUZ is designated as Chief, ARMD.'
  },
  {
    id: 'ord-402',
    orderNumber: 'SO-ITMS-2024-088',
    orderType: 'Special Order',
    subject: 'Detail of Cyber Threat Incident Response Team for National Cyber Drill 2024',
    issuedDate: '2024-03-01',
    effectiveDate: '2024-03-05',
    signatory: 'PCOL RODRIGO S DELA CRUZ JR',
    signatoryTitle: 'Chief, ARMD',
    status: 'Active',
    affectedPersonnelCount: 12,
    description: 'Deploys personnel from CSD, SDD, and NDCMD to participate in the National Inter-Agency Cyber Exercise.'
  },
  {
    id: 'ord-403',
    orderNumber: 'MO-ITMS-2024-012',
    orderType: 'Movement Order',
    subject: 'Temporary Detail of PLT John Mark Torres to RITMO 4A',
    issuedDate: '2023-11-01',
    effectiveDate: '2023-11-10',
    signatory: 'PBGEN BENJAMIN H ACORDA',
    signatoryTitle: 'Director, ITMS',
    status: 'Active',
    affectedPersonnelCount: 1,
    description: 'Temporary detail for installation and configuration of Regional Data Center in PRO4A.'
  },
  {
    id: 'ord-404',
    orderNumber: 'CO-ITMS-2023-099',
    orderType: 'Commendation Order',
    subject: 'Awarding of Medalya ng Kasanayan to SDD Software Development Team',
    issuedDate: '2023-12-15',
    effectiveDate: '2023-12-15',
    signatory: 'PBGEN BENJAMIN H ACORDA',
    signatoryTitle: 'Director, ITMS',
    status: 'Active',
    affectedPersonnelCount: 6,
    description: 'For outstanding performance in developing the PNP National Crime Reporting Portal ahead of schedule.'
  }
];

export const INITIAL_TRAINING = [
  {
    id: 'trn-501',
    personnelId: 'pnp-001',
    courseName: 'Police Senior Executive Course (PSEC)',
    category: 'Career Course',
    provider: 'National Police College (NPC)',
    startDate: '2019-02-01',
    completionDate: '2019-11-30',
    hours: 720,
    certificateNo: 'NPC-PSEC-2019-088'
  },
  {
    id: 'trn-502',
    personnelId: 'pnp-002',
    courseName: 'Advanced Threat Hunting & Incident Response',
    category: 'Cyber Security',
    provider: 'SANS Institute / DICT Cyber Academy',
    startDate: '2023-06-01',
    completionDate: '2023-06-25',
    hours: 120,
    certificateNo: 'SANS-SEC504-2023'
  },
  {
    id: 'trn-503',
    personnelId: 'pnp-003',
    courseName: 'Cloud-Native Enterprise Architecture Masterclass',
    category: 'Specialized IT',
    provider: 'Amazon Web Services Training & Certification',
    startDate: '2023-08-10',
    completionDate: '2023-08-28',
    hours: 80,
    certificateNo: 'AWS-ARCH-9941'
  },
  {
    id: 'trn-504',
    personnelId: 'pnp-004',
    courseName: 'Core Router & Data Center Networking (CCNP)',
    category: 'Network & Telecom',
    provider: 'Cisco Systems Academy',
    startDate: '2022-10-05',
    completionDate: '2022-12-15',
    hours: 160,
    certificateNo: 'CSCO-CCNP-88321'
  }
];

export const INITIAL_LEAVE = [
  {
    id: 'lve-601',
    personnelId: 'pnp-004',
    leaveType: 'Vacation',
    startDate: '2026-07-20',
    endDate: '2026-07-25',
    days: 5,
    status: 'Approved',
    approvedBy: 'PCOL RODRIGO S DELA CRUZ JR',
    purpose: 'Annual mandatory wellness leave'
  },
  {
    id: 'lve-602',
    personnelId: 'pnp-007',
    leaveType: 'Study',
    startDate: '2026-08-01',
    endDate: '2026-08-15',
    days: 10,
    status: 'Approved',
    approvedBy: 'PCOL RODRIGO S DELA CRUZ JR',
    purpose: 'Comprehensive Examination Review for Masterate Program'
  },
  {
    id: 'lve-603',
    personnelId: 'pnp-005',
    leaveType: 'Mandatory',
    startDate: '2026-06-10',
    endDate: '2026-06-15',
    days: 5,
    status: 'Completed',
    approvedBy: 'PCOL RODRIGO S DELA CRUZ JR'
  }
];
