import mongoose from 'mongoose';

const PersonnelSchema = new mongoose.Schema({
  id: { type: String, unique: true, sparse: true },
  rank: { type: String, default: '' },
  rankFullName: { type: String },
  firstName: { type: String, required: true },
  middleName: { type: String, default: '' },
  lastName: { type: String, required: true },
  qualifier: { type: String, default: '' },
  fullName: { type: String, default: '' },
  badgeNo: { type: String, default: '' },
  rankCategory: { type: String, enum: ['PCO', 'PNCO', 'NUP'], default: 'PNCO' },
  salaryGrade: { type: String, default: '' },
  plantilla: { type: String },
  positionCategory: { type: String, enum: ['Main', 'In Addition/Concurrent'], default: 'Main' },
  unitCategory: { type: String, default: 'ITMS HQ' },
  subUnitCategory: { type: String, default: 'Division' },
  sub_unit: { type: String, default: '' },
  details: { type: String, default: '' },
  station: { type: String, default: '' },
  division: { type: String, default: '' },
  detail: { type: String },
  designation: { type: String },
  address: { type: String },
  gender: { type: String },
  contactNumber: { type: String },
  birthday: { type: String },
  dateOfEntry: { type: String },
  enterInOfficerPositionDate: { type: String },
  designationDate: { type: String },
  effectiveDate: { type: String },
  lastPromotionDate: { type: String },
  status: { type: String, default: 'Active' },
  avatarUrl: { type: String },
  officeDivision: { type: String },
  qualification: { type: String },
  ageToDate: { type: String },
  birthdate: { type: String },
  ageOfServiceToDate: { type: String },
  desUp: { type: String },
  pnco: { type: String },
  nup: { type: String },
  // 34-column official fields
  civilStatus: { type: String },
  civil_status: { type: String },
  religion: { type: String },
  email: { type: String },
  tin: { type: String },
  gsisNumber: { type: String },
  gsis_number: { type: String },
  philHealthNo: { type: String },
  phil_health_no: { type: String },
  pagibigNo: { type: String },
  pagibig_no: { type: String },
  sourceOfCommissionship: { type: String },
  source_of_commissionship: { type: String },
  dateOfOfficershipOrCommission: { type: String },
  date_of_officership_or_commission: { type: String },
  pstatus: { type: String },
  pstatusDate: { type: String },
  pstatus_date: { type: String },
  rankStatus: { type: String },
  rank_status: { type: String },
  unitCode: { type: String },
  unit_code: { type: String },
  unit: { type: String },
  subUnitCode: { type: String },
  sub_unit_code: { type: String },
  stationCode: { type: String },
  station_code: { type: String },
  subStationCode: { type: String },
  sub_station_code: { type: String },
  subStation: { type: String },
  sub_station: { type: String },
  dateEnteredService: { type: String },
  date_entered_service: { type: String },
  badge_number: { type: String },
  sourceLink: { type: String },
  accountNumber: { type: String },
  source_link: { type: String },
  account_number: { type: String },
  first_name: { type: String },
  last_name: { type: String },
  middle_name: { type: String },
  phone_number: { type: String },
  designation_date: { type: String },
  last_promotion_date: { type: String }
}, {
  timestamps: true
});

export const PersonnelModel = mongoose.model('Personnel', PersonnelSchema);
